/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V1RouteImport } from './routes/v1'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MindRouteImport } from './routes/mind'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BeyondRouteImport } from './routes/beyond'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const V1Route = V1RouteImport.update({
  id: '/v1',
  path: '/v1',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondRoute = BeyondRouteImport.update({
  id: '/beyond',
  path: '/beyond',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beyond': typeof BeyondRoute
  '/contact': typeof ContactRoute
  '/mind': typeof MindRoute
  '/music': typeof MusicRoute
  '/projects': typeof ProjectsRoute
  '/songs': typeof SongsRoute
  '/v1': typeof V1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beyond': typeof BeyondRoute
  '/contact': typeof ContactRoute
  '/mind': typeof MindRoute
  '/music': typeof MusicRoute
  '/projects': typeof ProjectsRoute
  '/songs': typeof SongsRoute
  '/v1': typeof V1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beyond': typeof BeyondRoute
  '/contact': typeof ContactRoute
  '/mind': typeof MindRoute
  '/music': typeof MusicRoute
  '/projects': typeof ProjectsRoute
  '/songs': typeof SongsRoute
  '/v1': typeof V1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beyond'
    | '/contact'
    | '/mind'
    | '/music'
    | '/projects'
    | '/songs'
    | '/v1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beyond'
    | '/contact'
    | '/mind'
    | '/music'
    | '/projects'
    | '/songs'
    | '/v1'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beyond'
    | '/contact'
    | '/mind'
    | '/music'
    | '/projects'
    | '/songs'
    | '/v1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BeyondRoute: typeof BeyondRoute
  ContactRoute: typeof ContactRoute
  MindRoute: typeof MindRoute
  MusicRoute: typeof MusicRoute
  ProjectsRoute: typeof ProjectsRoute
  SongsRoute: typeof SongsRoute
  V1Route: typeof V1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v1': {
      id: '/v1'
      path: '/v1'
      fullPath: '/v1'
      preLoaderRoute: typeof V1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyond': {
      id: '/beyond'
      path: '/beyond'
      fullPath: '/beyond'
      preLoaderRoute: typeof BeyondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BeyondRoute: BeyondRoute,
  ContactRoute: ContactRoute,
  MindRoute: MindRoute,
  MusicRoute: MusicRoute,
  ProjectsRoute: ProjectsRoute,
  SongsRoute: SongsRoute,
  V1Route: V1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
